### PR TITLE
[464452] Fixed issues introduced by a VIATRA-MT API break

### PR DESCRIPTION
**Pull request by david-istvan**

### CODE REVIEW

**Comment by abelhegedus** [comment]
test this please

**Comment by abelhegedus** [comment]
@iqlabs-build retest this please

**Comment by abelhegedus** [comment]
@iqlabs-build test this please

**Comment by abelhegedus** [comment]
retest this please (strange proxy error)

**Comment by ujhelyiz** [comment]
retest this please (hope the error is fixed now)

**Comment by ujhelyiz** [comment]
Ok, transient error seems to be fixed, and as I am not sure whether an email was sent out, I am asking @david-istvan to look at it please (there is a link on the pull request page).

Furthermore, please, do not continue branches with pull requests, as they are introduced in the original requests  (see also the pull request page, if the description is not clear)..

**Comment by abelhegedus** [comment]
retest this please (viatra url fixed in job config)

**Pull request merged**
