### PR TITLE
Viatra transformation

### PR DESCRIPTION
**Pull request by lunkpeter**
Implemented VIATRA based QRT Transformation

### CODE REVIEW

**Comment by ujhelyiz** [comment]
ok to test

**Comment by ujhelyiz** [comment]
retest this please

**Comment by ujhelyiz** [comment]
retest this please

**Comment by abelhegedus** [comment]
retest this please

**Comment by abelhegedus** [comment]
test this please

**Comment by ujhelyiz** [comment]
test this please

**Comment by ujhelyiz** [comment]
retest this please

**Comment by ujhelyiz** [comment]
retest this please

**Pull request merged**
