### PR TITLE
Updating to IncQuery 1.0

### PR DESCRIPTION
**Pull request by ujhelyiz**
Changed version requirements - is there anything else needed?

### CODE REVIEW

**Comment by abelhegedus** [comment]
Thanks for the changes. Some comments:
* I think keeping strict version dependencies would be better: [1.0.0,1.1.0)
* Did you intentionally leave the deprecated engine creation methods?

**Comment by ujhelyiz** [comment]
I have updated the pull request with the required changes. For IncQuery I have kept the extrastrict requirements asked (although generally [1.0.0,2.0.0) is the more preferred).
And I have left some deprecated engine creation methods in, because there were a lot of them (17 to be precise :) ), and the code was full with warnings, so I did not found them at first.

**Comment by ujhelyiz** [comment]
Also updated Maven and Oomph config; I hope it works. :)

**Comment by abelhegedus** [comment]
Please fix 1,1.0 version to 1.1.0: https://github.com/IncQueryLabs/incquery-examples-cps/pull/18/files#diff-7e2a0ec8a1fb39587e4286e6b6d87e22R14

This seems to be a single error, the other changes are ok.

**Comment by ujhelyiz** [comment]
Fixed.

**Comment by abelhegedus** [comment]
Thanks!

**Pull request merged**
